Repository daangn/KarrotListKit, pull requests merged in 2024-04, with the labels that each got.

#37 NO-JIRA Then 의존성을 제거해요
  KarrotListKit.podspec
  Package.resolved
  Package.swift
  Sources/KarrotListKit/Adapter/CollectionViewAdapter.swift
  Sources/KarrotListKit/Layout/HorizontalLayout.swift
  Sources/KarrotListKit/Layout/VerticalGridLayout.swift
  Sources/KarrotListKit/Layout/VerticalLayout.swift
  Sources/KarrotListKit/Section.swift
  Sources/KarrotListKit/View/UICollectionComponentReusableView.swift
  Sources/KarrotListKit/View/UICollectionViewComponentCell.swift
  Tests/KarrotListKitTests/CollectionViewAdapterTests.swift
Labels: Improvement

#36 NO-JIRA README 의 DocC 문서 링크를 수정해요
  README.md
Labels: Docs

#38 MBP-4424 미구현된 `UIScrollViewDelegate` Event Modifier를 추가해요.
  Sources/KarrotListKit/Adapter/CollectionViewAdapter.swift
  Sources/KarrotListKit/Event/List/DidEndDeceleratingEvent.swift
  Sources/KarrotListKit/Event/List/DidEndDraggingEvent.swift
  Sources/KarrotListKit/Event/List/DidScrollToTopEvent.swift
  Sources/KarrotListKit/Event/List/WillBeginDeceleratingEvent.swift
  Sources/KarrotListKit/List.swift
  Tests/KarrotListKitTests/CollectionViewAdapterTests.swift
Labels: Feature

#39 [Support] If the header or footer is absent, a guide assertion failure occurs.
  Sources/KarrotListKit/Section.swift
Labels: Improvement
